name: SecondEnd
version: 1.0-SNAPSHOT
main: me.kingtux.secondend.SecondEnd
api-version: 1.16
authors: [ KingTux ]
depend: [Multiverse-Core]
description: Generates and resets a secondary end
commands:
  secondend:
    permission: "secondend.reset"
