name: ResourceWorlds
version: ${version}
main: me.kingtux.resourceworlds.ResourceWorlds
api-version: 1.16
authors: [ KingTux ]
softdepend: [ Multiverse-Core, Vault ]
description: Generates and resets a secondary end
commands:
  resourceworlds:
    description: "Second End Central Command"
    aliases: [ rw, rws ]